# Generated by Django 4.2.1 on 2023-05-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=400, verbose_name='Назва')),
                ('anons', models.TextField(max_length=400, verbose_name='Цитата')),
                ('full_text', models.TextField(verbose_name='Текст')),
            ],
        ),
    ]
