# Generated by Django 4.2.1 on 2023-05-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': False, 'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
    ]
