# Generated by Django 4.2.1 on 2023-05-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photolink_1',
            field=models.ImageField(default='photos/A224488_blog.jpg', upload_to='photos/', verbose_name='Посилання для 1 фото'),
        ),
        migrations.AddField(
            model_name='article',
            name='photolink_2',
            field=models.ImageField(default='photos/A224488_blog.jpg', upload_to='photos/', verbose_name='Посилання для 2 фото'),
        ),
    ]
